version: 2.1
executors:
  react-executor:
    docker:
      - image: circleci/node:11.3.0-browsers
    working_directory: ~/repo/react
jobs:
  react-build-test-dev:
    executor: react-executor
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Detect changed root files
          command: |
            if [[ $(git log --name-only --oneline -1 | sed 1d) != *\/* ]]; then
             circleci step halt
            fi
      - run:
          name: Detect changed subdirectory files
          command: |
            SUBDIR=$(git log --name-only --oneline -1 | sed 1d | grep '/' | cut -d "/" -f1 | sed '/^\.circleci$/d' | sort -u)
            if [[ "$SUBDIR" != *"react"* ]]; then
              circleci step halt
            fi
      - restore_cache:
          paths:
            - node_modules
          key: v018-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - run: yarn test
      - run:
          name: Execute pre-auth e2e tests
          command: yarn run test:e2e-public
          environment:
            CI_ENV: dev
      - run:
          name: Execute post-auth e2e tests
          command: yarn run test:e2e-private
          environment:
            CI_ENV: dev
      - run:
          name: Build web client for acceptance testing
          command: |
            NODE_PATH=./src \
            REACT_APP_COGNITO_POOL_ID=$REACT_APP_COGNITO_POOL_ID_DEV \
            REACT_APP_COGNITO_CLIENT_ID=$REACT_APP_COGNITO_CLIENT_ID_DEV \
            REACT_APP_HOST_ENV=dev \
            REACT_APP_TEST_VERSION=$(node -p "require('./package.json').version") \
            REACT_APP_TEST_BRANCH=$CIRCLE_BRANCH \
            REACT_APP_TEST_BUILD_NUMBER=$CIRCLE_BUILD_NUM \
            REACT_APP_BUILD_URL=$CIRCLE_BUILD_URL \
            REACT_APP_TEST_DEVELOPER=$CIRCLE_USERNAME \
            node node_modules/react-scripts/scripts/build.js
      - save_cache:
          paths:
            - node_modules
          key: v018-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: build
          paths:
            - .
  react-deploy-dev:
    executor: react-executor
    steps:
      - run:
          name: Update
          working_directory: /
          command: |
            sudo apt-get update -y
      - run:
          name: Upgrade
          working_directory: /
          command: |
            sudo apt-get upgrade -y
      - run:
          name: Install python and awscli
          working_directory: /
          command: |
            sudo apt-get install -yq python-dev python-pip --fix-missing
            sudo pip install awscli
      - attach_workspace:
          at: build
      - run:
          name: Exit if build directory NOT present after early client build termination
          #from build/ attached above
          command: |
            if [[ -f build/index.html ]]; then
              aws s3 sync build/ s3://mxfactorial-react-dev --delete
            else
               circleci step halt
            fi
      - run:
          name: Deploy to S3
          #from build/ attached above
          command: aws s3 sync build/ s3://mxfactorial-react-dev --delete
      - run:
          name: Change aws configuration
          command: aws configure set preview.cloudfront true
      - run:
          name: Terminate cache for dev distribution
          command: |
            aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID_DEV \
            --paths "/*" --query 'Invalidation.{Status:Status,CreateTime:CreateTime}'
  react-build-test-prod:
    executor: react-executor
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Detect changed root files
          command: |
            if [[ $(git log --name-only --oneline -1 | sed 1d) != *\/* ]]; then
             circleci step halt
            fi
      - run:
          name: Detect changed subdirectory files
          command: |
            SUBDIR=$(git log --name-only --oneline -1 | sed 1d | grep '/' | cut -d "/" -f1 | sed '/^\.circleci$/d' | sort -u)
            if [[ "$SUBDIR" != *"react"* ]]; then
              circleci step halt
            fi
      - restore_cache:
          paths:
            - node_modules
          key: v018-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - run: yarn test
      - run:
          name: Execute pre-auth e2e tests
          command: yarn run test:e2e-public
          environment:
            CI_ENV: prod
      - run:
          name: Execute post-auth e2e tests
          command: yarn run test:e2e-private
          environment:
            CI_ENV: prod
      - run:
          name: Build web client for prod environment
          command: yarn run build
      - save_cache:
          paths:
            - node_modules
          key: v018-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: build
          paths:
            - .
  react-deploy-prod:
    executor: react-executor
    steps:
      - run:
          name: Update
          working_directory: /
          command: |
            sudo apt-get update -y
      - run:
          name: Upgrade
          working_directory: /
          command: |
            sudo apt-get upgrade -y
      - run:
          name: Install python and awscli
          working_directory: /
          command: |
            sudo apt-get install -yq python-dev python-pip --fix-missing
            sudo pip install awscli
      - checkout:
          path: ~/repo
      - attach_workspace:
          at: build
      - run:
          name: Deploy to S3
          #from build/ attached above
          command: aws s3 sync build/ s3://mxfactorial-react-prod --delete
      - run:
          name: Change aws configuration
          command: aws configure set preview.cloudfront true
      - run:
          name: Terminate cache for distribution WITHOUT www prefix
          command: |
            aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
            --paths "/*" --query 'Invalidation.{Status:Status,CreateTime:CreateTime}'
      - run:
          name: Terminate cache for distribution WITH www prefix
          command: |
            aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_WWW_DISTRIBUTION_ID \
            --paths "/*" --query 'Invalidation.{Status:Status,CreateTime:CreateTime}'
  test-graphql-faas:
    docker:
      - image: circleci/node:11.3.0-browsers
    working_directory: ~/repo/graphql-faas
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Detect changed root files
          command: |
            if [[ $(git log --name-only --oneline -1 | sed 1d) != *\/* ]]; then
             circleci step halt
            fi
      - run:
          name: Detect changed subdirectory files
          command: |
            SUBDIR=$(git log --name-only --oneline -1 | sed 1d | grep '/' | cut -d "/" -f1 | sed '/^\.circleci$/d' | sort -u)
            if [[ "$SUBDIR" != *"graphql-faas"* ]]; then
              circleci step halt
            fi
      - run:
          name: Update
          working_directory: /
          command: |
            sudo apt-get update -y
      - run:
          name: Upgrade
          working_directory: /
          command: |
            sudo apt-get upgrade -y
      - run:
          name: Install python and awscli
          working_directory: /
          command: |
            sudo apt-get install -yq python-dev python-pip --fix-missing
            sudo pip install awscli
      - run: yarn install
      - run: yarn run deploy:dev

workflows:
  version: 2.1
  react-build-test-deploy-dev:
    jobs:
      - react-build-test-dev:
          filters:
            tags:
              only: /.*accept.*/
      - react-deploy-dev:
          requires:
            - react-build-test-dev
          filters:
            branches:
              ignore: /.*/
            # deploy accept tags only
            tags:
              only:
                - /.*accept.*/
  react-build-test-deploy-prod:
    jobs:
      - react-build-test-prod:
          filters:
            branches:
              only:
                - master
      - react-deploy-prod:
          requires:
            - react-build-test-prod
          filters:
            branches:
              only:
                - master
  graphql-test-faas-dev:
    jobs:
      - test-graphql-faas:
          filters:
            branches:
              only:
                - /^(master.+|(?!master).*)$/