version: 2.1
executors:
  react-executor:
    docker:
      - image: circleci/node:11.3.0-browsers
    working_directory: ~/repo/react
jobs:
  react-build-test-dev:
    executor: react-executor
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Update Linux packages and install aws cli
          working_directory: /
          command: |
            sudo apt-get update -y
            sudo apt-get upgrade -y
            sudo apt-get install -yq python-dev python-pip jq --fix-missing
            sudo pip install awscli
      - run:
          name: Detect changed subdirectory files since last successful build
          command: |
            . ../.circleci/scripts/detect-project.sh react
      - restore_cache:
          paths:
            - node_modules
          key: v019-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - run: yarn test
      - run:
          name: e2e tests
          command: bash test-e2e.sh dev
      - run:
          name: Build web client for acceptance testing
          command: bash build.sh dev
      - save_cache:
          paths:
            - node_modules
          key: v019-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - build
            - deploy.sh
  react-deploy-dev:
    executor: react-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Exit if build directory NOT present after early client build termination
          #from build/ attached above
          command: |
            if [[ ! -f build/index.html ]]; then
              circleci step halt
            fi
      - run:
          name: Update Linux packages and install aws cli
          working_directory: /
          command: |
            sudo apt-get update -y
            sudo apt-get upgrade -y
            sudo apt-get install -yq python-dev python-pip --fix-missing
            sudo pip install awscli
      - run:
          name: Deploy to S3 and terminate cache
          #from build/ attached above
          command: bash deploy.sh dev
  react-build-test-prod:
    executor: react-executor
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Update Linux packages and install aws cli
          working_directory: /
          command: |
            sudo apt-get update -y
            sudo apt-get upgrade -y
            sudo apt-get install -yq python-dev python-pip jq --fix-missing
            sudo pip install awscli
      - run:
          name: Detect changed subdirectory files since last successful build
          command: |
            . ../.circleci/scripts/detect-project.sh react
      - restore_cache:
          paths:
            - node_modules
          key: v019-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - run: yarn test
      - run:
          name: e2e tests
          command: bash test-e2e.sh prod
      - run:
          name: Build web client for prod environment
          command: bash build.sh prod
      - save_cache:
          paths:
            - node_modules
          key: v019-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - build
            - deploy.sh
  react-deploy-prod:
    executor: react-executor
    steps:
      - checkout:
          path: ~/repo
      - attach_workspace:
          at: .
      - run:
          name: Exit if build directory NOT present after early client build termination
          #from build/ attached above
          command: |
            if [[ ! -f build/index.html ]]; then
              circleci step halt
            fi
      - run:
          name: Update Linux packages and install aws cli
          working_directory: /
          command: |
            sudo apt-get update -y
            sudo apt-get upgrade -y
            sudo apt-get install -yq python-dev python-pip --fix-missing
            sudo pip install awscli
      - run:
          name: Deploy to S3 and terminate cache
          #from build/ attached above
          command: bash deploy.sh prod
  services-dev:
    docker:
      - image: circleci/node:11.3.0-browsers
    working_directory: ~/repo/services
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Update Linux packages and install aws cli
          working_directory: /
          command: |
            sudo apt-get update -y
            sudo apt-get upgrade -y
            sudo apt-get install -yq python3 python3-pip jq --fix-missing
            pip3 install awscli --upgrade --user
            sudo cp -rf $HOME/.local/bin/* /usr/local/bin
      - run:
          name: Detect changed subdirectory files since last successful build
          command: |
            . ../.circleci/scripts/detect-project.sh services
      - run:
          name: Install and configure go
          working_directory: /
          command: |
            . ~/repo/.circleci/scripts/get-go.sh
            source /home/circleci/.bashrc
      - run:
          name: Install dependencies, archive, then deploy
          command: bash deploy.sh dev
      - run:
          name: Test dev endpoints
          working_directory: ~/repo/services/graphql-faas
          command: bash test-all.sh dev
  services-qa:
    docker:
      - image: circleci/node:11.3.0-browsers
    working_directory: ~/repo/services
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Update Linux packages and install aws cli
          working_directory: /
          command: |
            sudo apt-get update -y
            sudo apt-get upgrade -y
            sudo apt-get install -yq python-dev python-pip jq --fix-missing
            sudo pip install awscli
      - run:
          name: Detect changed subdirectory files since last successful build
          command: |
            . ../.circleci/scripts/detect-project.sh services
      - run:
          name: Install and configure go
          working_directory: /
          command: |
            . ~/repo/.circleci/scripts/get-go.sh
            source /home/circleci/.bashrc
      - run:
          name: Install dependencies, archive, then deploy
          command: bash deploy.sh qa
      - run:
          name: Test qa endpoints
          working_directory: ~/repo/services/graphql-faas
          command: bash test-all.sh qa
  services-prod:
    docker:
      - image: circleci/node:11.3.0-browsers
    working_directory: ~/repo/services
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Update Linux packages and install aws cli
          working_directory: /
          command: |
            sudo apt-get update -y
            sudo apt-get upgrade -y
            sudo apt-get install -yq python-dev python-pip jq --fix-missing
            sudo pip install awscli
      - run:
          name: Detect changed subdirectory files since last successful build
          command: |
            . ../.circleci/scripts/detect-project.sh services
      - run:
          name: Install and configure go
          working_directory: /
          command: |
            . ~/repo/.circleci/scripts/get-go.sh
            source /home/circleci/.bashrc
      - run:
          name: Install dependencies, archive, then deploy
          command: bash deploy.sh prod

workflows:
  version: 2.1
  react-build-test-deploy-dev:
    jobs:
      - react-build-test-dev:
          filters:
            tags:
              only: /.*accept.*/
      - react-deploy-dev:
          requires:
            - react-build-test-dev
          # filters:
          #   branches:
          #     ignore: /.*/
          # deploy accept tags only
          # tags:
          #   only:
          #     - /.*accept.*/
  react-build-test-deploy-prod:
    jobs:
      - react-build-test-prod:
          filters:
            branches:
              only:
                - master
      - react-deploy-prod:
          requires:
            - react-build-test-prod
          filters:
            branches:
              only:
                - master
  services:
    jobs:
      - services-dev:
          filters:
            branches:
              only:
                - /^(master.+|(?!master).*)$/
      - services-prod:
          filters:
            branches:
              only:
                - master
