version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          paths:
            - react/node_modules
          key: v2-dependencies-{{ checksum "react/package.json" }}
      - run: cd react && npm install
      - run: cd react && npm test
      - run: cd react && npm run ci:e2e-private
      - run: cd react && npm run ci:e2e-public
      - save_cache:
          paths:
            - react/node_modules
          key: v2-dependencies-{{ checksum "react/package.json" }}
  deploy:
    docker:
      - image: circleci/node:latest-browsers
    working_directory: ~/repo
    steps:
      - run:
          name: Update
          working_directory: /
          command: |
            sudo apt-get update -y
      - run:
          name: Upgrade
          working_directory: /
          command: |
            sudo apt-get upgrade -y
      - run:
          name: Install python and awscli
          working_directory: /
          command: |
            sudo apt-get install -yq python-dev python-pip --fix-missing
            sudo pip install awscli
      - checkout
      - run: cd react && npm install
      - run: cd react && npm run build
      - run:
          name: Deploy to S3
          command: aws s3 sync react/build/ s3://mxfactorial-web --delete
      - run:
          name: Change aws configuration
          command: aws configure set preview.cloudfront true
      - run:
          name: Terminate cache for distribution WITHOUT www prefix
          command: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
      - run:
          name: Terminate cache for distribution WITH www prefix
          command: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_WWW_DISTRIBUTION_ID --paths "/*"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
