version: 2
jobs:
  build-test-react:
    docker:
      - image: circleci/node:8.9.1-stretch-browsers
    working_directory: ~/repo/react
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Detect changed root files
          command: |
            if [[ $(git log --name-only --oneline -1 | sed 1d) != *\/* ]]; then
             circleci step halt
            fi
      - run:
          name: Detect changed subdirectory files
          command: |
            SUBDIR=$(git log --name-only --oneline -1 | sed 1d | grep '/' | cut -d "/" -f1 | sed '/^\.circleci$/d' | sort -u)
            if [[ "$SUBDIR" != *"react"* ]]; then
              circleci step halt
            fi
      - restore_cache:
          paths:
            - node_modules
          key: v5-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - run: npm test
      - run: npm run ci:e2e-private
      - run: npm run ci:e2e-public
      - save_cache:
          paths:
            - node_modules
          key: v5-dependencies-{{ checksum "package.json" }}
  deploy-react-prod:
    docker:
      - image: circleci/node:8.9.1-stretch-browsers
    working_directory: ~/repo/react
    steps:
      - run:
          name: Update
          working_directory: /
          command: |
            sudo apt-get update -y
      - run:
          name: Upgrade
          working_directory: /
          command: |
            sudo apt-get upgrade -y
      - run:
          name: Install python and awscli
          working_directory: /
          command: |
            sudo apt-get install -yq python-dev python-pip --fix-missing
            sudo pip install awscli
      - checkout:
          path: ~/repo
      - run: npm install
      - run: npm run build
      - run:
          name: Deploy to S3
          command: aws s3 sync react/build/ s3://mxfactorial-react-prod --delete
      - run:
          name: Change aws configuration
          command: aws configure set preview.cloudfront true
      - run:
          name: Terminate cache for distribution WITHOUT www prefix
          command: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
      - run:
          name: Terminate cache for distribution WITH www prefix
          command: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_WWW_DISTRIBUTION_ID --paths "/*"
  test-graphql-faas:
    docker:
      - image: circleci/node:8.9.1-stretch-browsers
    working_directory: ~/repo/graphql-faas
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Detect changed root files
          command: |
            if [[ $(git log --name-only --oneline -1 | sed 1d) != *\/* ]]; then
             circleci step halt
            fi
      - run:
          name: Detect changed subdirectory files
          command: |
            SUBDIR=$(git log --name-only --oneline -1 | sed 1d | grep '/' | cut -d "/" -f1 | sed '/^\.circleci$/d' | sort -u)
            if [[ "$SUBDIR" != *"graphql-faas"* ]]; then
              circleci step halt
            fi
      - run:
          name: Update
          working_directory: /
          command: |
            sudo apt-get update -y
      - run:
          name: Upgrade
          working_directory: /
          command: |
            sudo apt-get upgrade -y
      - run:
          name: Install python and awscli
          working_directory: /
          command: |
            sudo apt-get install -yq python-dev python-pip --fix-missing
            sudo pip install awscli
      - run: npm install
      - run: npm run deploy:dev

workflows:
  version: 2
  react-build-test:
    jobs:
      - build-test-react
      - deploy-react-prod:
          requires:
            - build-test-react
          filters:
            branches:
              only: master
  graphql-test-faas-dev:
    jobs:
      - test-graphql-faas:
          filters:
            branches:
              only:
                # prior art: https://stackoverflow.com/a/49515208
                - /^(master.+|(?!master).*)$/
